### ISSUE TITLE
Anyway to simplify answer with one isinstance statement?

### ISSUE THREAD

**Issue by jordan-gillard** [rmotr-curriculum/introduction-to-python-programming-questions#18]
Can this problem be solved with something like:
if isinstance(i, int) for i in (a, b):
    return True

I solved this with two isinstance statements, but it seems redundant. The code above did not work. Im pretty much asking if you can have an isinstance function handle multiple objects and one classinfo argument.

**Comment by jangeador** [comment]
If the parameters were in a list you could use `all()` to check all the parameters in one statement.
