### ISSUE TITLE
Test With Valid String-RUN TEST

### ISSUE THREAD

**Issue by amueke** [rmotr-curriculum/introduction-to-python-programming-questions#47]
It is not working, any help?

**Assignment**: http://learn.rmotr.com/python/introduction-to-programming-with-python/getting-started/append-x

**User code**:
```python
def append_x(a_string):
    return a_string
    if a_string == '':
        append_x('abc_') ==append_x('abc_x')
```

**Comment by ajuchem** [comment]
See if this helps:
If the `a_string` is an empty string, just `return` it. Otherwise, `return` the `a_string` with an `'x' `added to it.

Tip: note I didn't say 'appended' to the 'string' as we can't `append` a `string`.

**Comment by santiagobasulto** [comment]
@ajuchem provided a good alternative! @amueke as a general recommendation. DON'T invoke your functions inside your functions. You have ´append_x´ inside the ´append_x´ definition. NOT A GOOD IDEA!
