### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Alex-Guha** [rmotr-curriculum/introduction-to-python-programming-questions#49]
What do you (the teacher) want in terms of code? I didn't quite understand what was being asked. I kinda cheated and just did the below.

**Assignment**: http://learn.rmotr.com/python/introduction-to-programming-with-python/getting-started/powers-of-2

**User code**:
```python
def powers_of_2(power):
    return 2**power
```

**Comment by santiagobasulto** [comment]
That works!
