### ISSUE TITLE
As a non-coder, I am not sure what I am doing wrong

### ISSUE THREAD

**Issue by webtech-pmp** [rmotr-curriculum/introduction-to-python-programming-questions#50]
I get a lot of red error messages.

**Assignment**: http://learn.rmotr.com/python/introduction-to-programming-with-python/getting-started/append-x

**User code**:
```python
def append_x(a_string):
    if a_string != '':
        append_x(a_string) == ''
    else:
        a_string = a_string + "_x"

```

**Comment by ajuchem** [comment]
You are on the right path on the if/else statement.
If the `a_string` is an empty string, just `return` it. Otherwise, `return` the `a_string` with an `'x' `added to it.

Tip: note I didn't say 'appended' to the 'string' as we can't `append` a `string`.

**Comment by santiagobasulto** [comment]
Please show us the errors.
