### ISSUE TITLE
How to add string type text to string?

### ISSUE THREAD

**Issue by webtech-pmp** [rmotr-curriculum/introduction-to-python-programming-questions#51]
I tried the plus sign but when I run it I get error on the run test, run code doesn't do anything

**Assignment**: http://learn.rmotr.com/python/introduction-to-programming-with-python/getting-started/append-x

**User code**:
```python
def append_x(a_string):
    if a_string == '':
        return ''
    elif a_string != '':
        return a_string + "_x"
```

**Comment by ajuchem** [comment]
You are almost there!
You are on the right path on the `if`/`else` statement.
If the `a_string` is an empty string, just `return` it. Otherwise, `return` the `a_string` with an `'x' `added to it.

**Comment by santiagobasulto** [comment]
Please show us the error Nancy, I think it might be an indentation error.
