### ISSUE TITLE
Is order important on this one?

### ISSUE THREAD

**Issue by vbchick712** [rmotr-curriculum/introduction-to-python-programming-questions#53]
I had essentially the correct answer but my boolean was the final elif and it never passed the test until I put my answer in the exact order that the solution is in. Does that mean that the order of testing the instance of an object is important on this one?

**Assignment**: http://learn.rmotr.com/python/introduction-to-programming-with-python/getting-started/return-the-type-of-value

**User code**:
```python
# My code that throws an error but follows the prompts of the question
def which_type(val):
    if isinstance(val, int):
        return 'integer'
    elif isinstance(val, str):
        return 'string'
    elif isinstance(val, float):
        return 'float'
    elif isinstance(val, bool):
        return 'boolean'
```

**Comment by santiagobasulto** [comment]
@vbchick712 great question! It does matter, specially when checking these types. Check this post for further details about booleans: https://blog.rmotr.com/those-tricky-python-booleans-2100d5df92c
