### ISSUE TITLE
Returning the else when all nums are int

### ISSUE THREAD

**Issue by MightBeWrong** [rmotr-curriculum/introduction-to-python-programming-questions#55]
Why would this be returning 'not an int' when all the num in a_list are int? 

EDIT: Question was answered by Mr. Symons. Code was not in the form of an if/else. It now runs successfully.

**Assignment**: http://learn.rmotr.com/python/introduction-to-programming-with-python/loops-and-collections/sum-if-list-only-contains-integers

**User code**:
```python
def sum_if_list_of_ints(a_list):
    list_sum = 0
    
    for num in a_list:
        if isinstance(num, int):
            list_sum += num
        return 'not an int'
    return list_sum
```

**Comment by martinzugnoni** [comment]
👍
